project:
  type: website
  output-dir: _site

website:
  title: "Dashboard"
  navbar:
    left:
      - href: weather_station.qmd
        text: Carde√±a
      # - href: ibex.qmd
      #   text: Ibex

format:
  dashboard:
    theme: journal