project:
  type: website
  output-dir: _site

website:
  title: "Dashboard"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: weather_station.qmd
        text: Carde√±a

format:
  dashboard:
    theme: journal